version: '3.3'

services:

  #postgres:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_PASSWORD: mysecretisapassword

  redis:
    image: redis:latest
    #command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    #volumes:
    #  - ./config/6379.conf:/usr/local/etc/redis/redis.conf
    network_mode: host

  rabbitmq:
    image: rabbitmq:latest
    #restart: always
    environment:
      RABBITMQ_DEFAULT_USER: puser
      RABBITMQ_DEFAULT_PASS: ppass
      RABBITMQ_DEFAULT_VHOST: pvhost
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: host

  web:
    build: .
    command: python follow-process/manage.py runserver 0.0.0.0:8000
    image: follow-process:latest
    volumes:
      - ./data:/follow-process/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    network_mode: host