"""
Django settings for followprocess project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# CELERY - Exec commands
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'followprocess.settings')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j!hs-$s2ot&m$x#kwxkbd9cf^#c7nkaru!pzi^8=#yw)sh95ss'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

IS_DOCKER = True

ALLOWED_HOSTS = ['*']

CSRF_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #Frameworks
    'rest_framework',
    'channels',

    #Internal apps
    'followprocess.process',
]

REDIS_SERVER    = ""
RABBITMQ_SERVER = ""
RABBITMQ_USER   = ""
RABBITMQ_PASS   = ""
RABBITMQ_VHOST  = ""

if IS_DOCKER:
    REDIS_SERVER    = "redis"
    RABBITMQ_SERVER = "rabbitmq"
    RABBITMQ_USER   = "puser"
    RABBITMQ_PASS   = "ppass"
    RABBITMQ_VHOST  = "pvhost"
else:
    REDIS_SERVER    = "127.0.0.1"
    RABBITMQ_SERVER = "127.0.0.1"
    RABBITMQ_USER   = "followprocess"
    RABBITMQ_PASS   = "followprocess"
    RABBITMQ_VHOST  = "followprocess_host"

#CELERY
BROKER_URL            = "amqp://"+RABBITMQ_USER+":"+RABBITMQ_PASS+"@"+RABBITMQ_SERVER+":5672/"+RABBITMQ_VHOST
CELERY_RESULT_BACKEND = "redis://"+REDIS_SERVER+":6379/0"

#CELERY_RESULT_SERIALIZER = 'json'
#CELERY_ACCEPT_CONTENT    = ['json']
#CELERY_TASK_SERIALIZER   = 'json'

CELERY_MAX_CACHED_RESULTS = -1

#APP - CONFIG
LOGIN_URL          = "/login"
LOGIN_REDIRECT_URL = '/home'

#WEBSOCKETS - DJANGO CHANNELS
ASGI_APPLICATION   = "followprocess.routing.application"
CHANNEL_LAYERS     = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis://"+REDIS_SERVER+":6379/1", 6379)],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'followprocess.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'followprocess/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'followprocess.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'data/db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = BASE_DIR + '/staticfiles'
STATIC_URL = '/static/'