# LEGACY
# FROM python:3.6

# #Adding files
# COPY ./requirements/requirements_base.txt ./requirements_base.txt
# COPY ./requirements/requirements_prod.txt ./requirements.txt
# ADD . /follow-process

# COPY ./compose/dev/entrypoint/entry.worker.sh /entry.worker.sh
# RUN chmod +x /entry.worker.sh

# COPY ./compose/dev/entrypoint/entry.startdjango.sh /entry.gunicorn.sh
# RUN chmod +x /entry.gunicorn.sh

# #Installing components
# RUN pip install -r requirements.txt

# WORKDIR /follow-process

# EXPOSE 8000

FROM alpine:latest

# LOCAL

#Create trivial app folder
#RUN mkdir follow-process \
# && mkdir follow-process/followprocess \
# && mkdir follow-process/scripts
#--

#Including/Copying main folders
#COPY ./requirements/requirements_prod.txt ./tmp/requirements_prod.txt
#COPY ./requirements/requirements_base_light.txt ./tmp/requirements.txt
#ADD manage.py /follow-process
#ADD followprocess /follow-process/followprocess
#--

#Installing resources && installing python modules
#COPY ./compose/prod/entryinstalling/entry.installing.tools.sh ./follow-process/scripts/
#COPY ./compose/prod/entrypoint/entry.gunicorn.sh ./follow-process/scripts/

#RUN chmod +x ./follow-process/scripts/entry.installing.tools.sh \
# && cp ./follow-process/scripts/entry.gunicorn.sh /tmp/entry.gunicorn.sh \
# && chmod +x /tmp/entry.gunicorn.sh \
# && ./follow-process/scripts/entry.installing.tools.sh 
#
#RUN pip install -r ./tmp/requirements_prod.txt \
#--

# ONLINE

#Installing resources ONLINE
RUN wget -O /tmp/entry.installing.tools.sh https://raw.githubusercontent.com/bernardopadua/follow-process/development/compose/lightdev/entryinstalling/entry.installing.tools.sh \
 && chmod +x /tmp/entry.installing.tools.sh \
 && ./tmp/entry.installing.tools.sh

#Creating project from git
RUN git clone --single-branch --branch development https://github.com/bernardopadua/follow-process.git

#Minor steps to complete && installing python modules
RUN chmod +x ./follow-process/compose/prod/entrypoint/entry.gunicorn.sh \
 && chmod +x ./follow-process/compose/prod/entrypoint/entry.worker.sh

RUN pip install -r ./follow-process/requirements/requirements_prod.txt
#--

COPY ./.env ./follow-process/.env

# BOTH

#Running DEV server
#EXPOSE 8000
WORKDIR /follow-process

CMD [ "./compose/prod/entrypoint/entry.gunicorn.sh" ]
#--
